### ISSUE TITLE
[Feature] Move the "change event date range" upstream

### ISSUE THREAD

**Issue by jon-openspace** [fivetran/dbt_amplitude#10]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently, "change event date range" does not apply to the staging models. Because of this, `dbt build` takes a very long time to complete. On my Amplitude Dataset, there are ~65M events since 2019, and it takes ~15 minutes to run the `amplitude` models. Most of this time is spent generating the staging models. 

### Describe alternatives you've considered

I created a temporary clone of the raw `event` table and pointed the package towards it, and that drastically reduced the amount of time it tool to build the models. However, I cannot do this programmatically with dbt, as we keep our raw tables in a separate snowflake database that the dbt role cannot write tables to.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jon-openspace thanks so much for opening this feature request!

I think this is a completely reasonable request and would greatly improve the performance of the package and downstream transformations. This would result in a bit different behavior for our staging models from our other packages (we typically try not to filter out data in the staging models); however, this package should be an exception since the event data can grow in volume and manage to be unusable with the run time if we don't filter out in the staging model.

I will accept this Feature and plan to provide an update once our team starts working on this. Thanks again!

**Comment by fivetran-reneeli** [comment]
Feature added in the latest release 
https://github.com/fivetran/dbt_amplitude_source
