### ISSUE TITLE
[Bug] Error in event enhanced incremental logic

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_amplitude#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

There have been reported cases where the incremental logic in the event enhanced model results in failures due to the [unique key](https://github.com/fivetran/dbt_amplitude/blob/30d8ec277d192fb7628e347d7ce2f7448a1a5c28/models/amplitude__event_enhanced.sql#L4) not being unique. This results in a duplicate row detected during incremental run and thus a corresponding runtime failure.

### Expected behavior

The incremental logic in the package works as expected.

### dbt Project configurations

No specific configs added

### Package versions

Latest

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### How are you running this dbt package?

Fivetran Quickstart Data Model

### dbt Version

Latest

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-catfritz** [comment]
@fivetran-joemarkiewicz The two sources that flow into `amplitude__event_enhanced` each have multi-field primary keys, so I believe we need to capture all of them since `event_type` is effectively left joined onto `event`.

In the [stg_amplitude__event_type](https://github.com/fivetran/dbt_amplitude_source/blob/main/models/stg_amplitude__event_type.sql#L46) model, we create  `unique_event_type_id` but don't use it downstream. Adding it to [this line](https://github.com/fivetran/dbt_amplitude/blob/30d8ec277d192fb7628e347d7ce2f7448a1a5c28/models/amplitude__event_enhanced.sql#L150) in place of `event_day` should create a unique key for merging on.

I tested this out with our test data, and while it ran on the incremental run successfully, it is very limited and I was not able to recreate the original issue. This might be a good candidate for an alpha release.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it's been addressed in the above PR.
